# Generated by Django 3.1.1 on 2020-11-14 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_postmodel_gif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='gif',
            field=models.ImageField(max_length=144, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
