# Generated by Django 3.1.1 on 2020-11-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20201114_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='audio',
            field=models.ImageField(default='brandon', max_length=144, upload_to='uploads/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
