# Generated by Django 3.1.1 on 2020-12-01 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20201130_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='finalVideo',
            field=models.FileField(default='hi', upload_to='uploads/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
