# Generated by Django 3.1.1 on 2020-12-06 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_postmodel_finalvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='gif',
            field=models.FileField(max_length=144, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
