# Generated by Django 3.1.1 on 2020-12-07 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20201206_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='header',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
